# Generated by Django 5.1.5 on 2025-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
    ]
